# Site settings
title: arjanfrans.com 
email: arjanfrans.com@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arjanfrans.com" # the base hostname & protocol for your site
twitter_username: arjanfrans
github_username:  arjanfrans
linkedin_username: arjanf
stackoverflow_page: "3280589/arjanf"

# Build settings
markdown: kramdown
